set_property PACKAGE_PIN F12 [get_ports {result[7]}]
set_property PACKAGE_PIN G12 [get_ports {result[6]}]
set_property PACKAGE_PIN G11 [get_ports {result[5]}]
set_property PACKAGE_PIN H11 [get_ports {result[4]}]
set_property PACKAGE_PIN F10 [get_ports {result[3]}]
set_property PACKAGE_PIN G10 [get_ports {result[2]}]
set_property PACKAGE_PIN H9 [get_ports {result[1]}]
set_property PACKAGE_PIN H10 [get_ports {result[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {result[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {result[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {result[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {result[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {result[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {result[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {result[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {result[0]}]
